<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latestMajor</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;IDE0051</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;IDE0051</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Weaver\**" />
    <EmbeddedResource Remove="Weaver\**" />
    <None Remove="Weaver\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Achievements\BlasterSwordAchievement.cs" />
    <Compile Remove="Achievements\WeightedAnkletAchievement.cs" />
    <Compile Remove="Artifacts\ArtifactOfIndecision.cs" />
    <Compile Remove="Artifacts\ArtifactOfUnstableForm.cs" />
    <Compile Remove="CoreModules\Stathooks.cs" />
    <Compile Remove="Effect\FaustOrb.cs" />
    <Compile Remove="Effect\HungeringConsumptionOrb.cs" />
    <Compile Remove="Equipment\ChaosBeacon.cs" />
    <Compile Remove="EliteEquipment\AffixBenevolent.cs" />
    <Compile Remove="EliteEquipment\AffixHungering.cs" />
    <Compile Remove="EliteEquipment\AffixHypercharged.cs" />
    <Compile Remove="EliteEquipment\AffixMagnetic.cs" />
    <Compile Remove="EliteEquipment\AffixRallying.cs" />
    <Compile Remove="EliteEquipment\AffixSteadfast.cs" />
    <Compile Remove="EliteEquipment\AffixTarred.cs" />
    <Compile Remove="Equipment\NanoweaveCapsule.cs" />
    <Compile Remove="Equipment\PheromoneSac.cs" />
    <Compile Remove="Equipment\SoulPin.cs" />
    <Compile Remove="Interactables\BuffBrazierOld.cs" />
    <Compile Remove="Interactables\BuffBrazierOldOld.cs" />
    <Compile Remove="Items\AlienMagnetRework.cs" />
    <Compile Remove="Items\BloodDiamond.cs" />
    <Compile Remove="Items\ObliterballAndChain.cs" />
    <Compile Remove="Items\RicochetTest.cs" />
    <Compile Remove="Items\Tier2\EmpathicResonator.cs" />
    <Compile Remove="Items\VoidItems\FrenziedWarbot.cs" />
    <Compile Remove="Items\VoidItems\PhasewindFeather.cs" />
    <Compile Remove="Items\VoidItems\RazorfinWing.cs" />
    <Compile Remove="Items\VoidItems\ScientistsNanites.cs" />
    <Compile Remove="Items\VoidItems\Shichishito.cs" />
    <Compile Remove="Items\VoidItems\UmbralAspis.cs" />
    <Compile Remove="Items\VoidItems\Tier1\ShatterSpike.cs" />
    <Compile Remove="StandaloneBuffs\DefensiveMatrix.cs" />
    <Compile Remove="StandaloneBuffs\StrengthOfThePack.cs" />
    <Compile Remove="StandaloneBuffs\Tier2\PrecisionProtocol.cs" />
    <Compile Remove="StandaloneBuffs\Tier3\SparkGap.cs" />
    <Compile Remove="Survivors\TestCharacter.cs" />
    <Compile Remove="Utils\Components\MaterialControllerComponentsGetter.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="AetheriumSounds.bnk" />
    <None Remove="AetheriumSounds.txt" />
    <None Remove="aetherium_assets" />
    <None Remove="Init.bnk" />
    <None Remove="Init.txt" />
    <None Remove="objexporter" />
    <None Remove="objexporter.manifest" />
    <None Remove="PluginInfo.xml" />
    <None Remove="SoundbanksInfo.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="AetheriumSounds.bnk" />
    <EmbeddedResource Include="aetherium_assets" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Items\VoidItems\Tier3\" />
    <Folder Include="Items\VoidItems\Tier2\" />
    <Folder Include="Skills\" />
    <Folder Include="States\Item\" />
    <Folder Include="States\Survivor\Koalesk\Misc\" />
    <Folder Include="States\Survivor\Koalesk\Special\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.0.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="RiskOfRain2.GameLibs" Version="1.3.6-r.0" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" />
    <PackageReference Include="MMHOOK.RoR2" Version="2024.12.10">
      <NoWarn>NU1701</NoWarn>
    </PackageReference>
    <PackageReference Include="R2API.RecalculateStats" Version="1.5.0" />
    <PackageReference Include="R2API.Director" Version="2.3.2" />
    <PackageReference Include="R2API.Elites" Version="1.0.*" />
    <PackageReference Include="R2API.Prefab" Version="1.0.*" />
    <PackageReference Include="R2API.DamageType" Version="1.1.*" />
    <PackageReference Include="R2API.Sound" Version="1.0.*" />
    <PackageReference Include="R2API.Core" Version="5.1.*" />
    <PackageReference Include="R2API.Items" Version="1.0.*" />
    <PackageReference Include="R2API.Unlockable" Version="1.0.*" />
    <PackageReference Include="R2API.CommandHelper" Version="1.0.*" />
    <PackageReference Include="R2API.Language" Version="1.0.*" />
    <PackageReference Include="R2API.Orb" Version="1.0.*" />
    <PackageReference Include="R2API.Networking" Version="1.0.*" />
  
  <PackageDownload Include="NETStandard.Library.Ref" Version="[2.1.0]" />
  </ItemGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="./weave.bat $(TargetDir)" />
  </Target>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="if not exist &quot;C:\Users\Jonathan Church\AppData\Roaming\r2modmanPlus-local\RiskOfRain2\profiles\Aetherium-Testing\BepInEx\plugins\KomradeSpectre-Aetherium\Language\en&quot; mkdir &quot;C:\Users\Jonathan Church\AppData\Roaming\r2modmanPlus-local\RiskOfRain2\profiles\Aetherium-Testing\BepInEx\plugins\KomradeSpectre-Aetherium\Language\en&quot;" />
  </Target>
	
</Project>